import type { NextPage } from "next";
import { GetStaticProps } from "next";
import Head from "next/head";
import { readdirSync, readFileSync } from "fs";
import matter from "gray-matter";
import Link from "next/link";
import { Card, Chips, Layout } from "@/components";
import { Post, BasicInfo } from "@/types/post";

const Home: NextPage<{ posts: Post[]; basicInfo: BasicInfo }> = ({
  posts,
  basicInfo,
}) => {
  return (
    <>
      <Head>
        <title>Blog</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        <div className="overflow-hidden w-full h-80 md:h-96 rounded-xl md:rounded-b-2xl relative mt-16">
          <img
            className="w-full"
            alt="hero-img"
            src="https://images.unsplash.com/photo-1656425311485-3c10dbcc9758?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxlZGl0b3JpYWwtZmVlZHwxOXx8fGVufDB8fHx8&auto=format&fit=crop&w=800&q=60"
          ></img>
          <div className="absolute z-10 w-full h-full top-0 flex flex-col justify-center items-center text-primary">
            <h1 className="display-small md:display-large">
              {basicInfo.title}
            </h1>
            <h4 className="title-large md:headline-medium mt-2">
              {basicInfo.introduce}
            </h4>
          </div>
        </div>
        <main className="container mx-auto flex flex-wrap items-stretch">
          {posts.map((post) => {
            return (
              <Card
                key={post.title}
                type="elevated"
                className="flex w-full md:w-auto md:basis-80 m-4 z-10 overflow-hidden flex-col shrink md:pb-5 cursor-pointer"
              >
                <Link href={`/blog/${post.pathName}`} passHref>
                  <a className="flex md:block">
                    {post.thumbnail && (
                      <div className="h-24 w-24 overflow-hidden rounded-xl md:w-full md:h-48">
                        <img
                          src={post.thumbnail}
                          alt={post.title}
                          className="w-full "
                        ></img>
                      </div>
                    )}
                    <div className="box-border px-6 flex flex-col justify-center">
                      <h1 className="title-medium md:headline-medium text-primary mt-1 md:mt-5">
                        {post.title}
                      </h1>
                      <h2 className="label-medium md:label-large text-secondary md:mt-2">
                        {post.abstract}
                      </h2>
                      <div className="md:mt-2">
                        {Array.isArray(post.tags) &&
                          post.tags.map((tag) => {
                            return (
                              <Chips
                                className="m-1"
                                icon="price-tag-3"
                                key={tag}
                                type="suggestion"
                              >
                                {tag}
                              </Chips>
                            );
                          })}
                      </div>
                    </div>
                  </a>
                </Link>
              </Card>
            );
          })}
        </main>
      </Layout>
    </>
  );
};

export const getStaticProps: GetStaticProps<any, any, Post[]> = async () => {
  const fileNames = readdirSync("posts");
  const posts = fileNames
    .filter((filename) => {
      const fileContent = readFileSync(`posts/${filename}`).toString();
      const { data } = matter(fileContent) || {};
      return data.visible !== false && filename.includes(".md");
    })
    .map((filename) => {
      const fileContent = readFileSync(`posts/${filename}`).toString();
      let pathName = filename.replace(".md", "");
      const { data } = matter(fileContent) || {};
      return {
        title: data.title || "",
        thumbnail: data.thumbnail || "",
        abstract: data.abstract || "",
        tags: data.tags || [],
        pathName,
      };
    }) as Post[];

  const basicInfo = {
    title: "SPD Blog",
    introduce: "life working with SPD",
  };
  return {
    props: {
      posts: posts,
      basicInfo,
    },
  };
};

export default Home;
